import "@/styles/globals.css";
import type { AppProps } from "next/app";
import NavBar from "./components/NavBar";
import Head from "next/head";
import { LanguageProvider } from "../public/LanguageContext";

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <LanguageProvider>
        <Head>
          <title>ApiSudex</title>
          <link rel="shortcut icon" href="logo.png" type="image/x-icon" />
          <meta name="description" content="" />
          <meta
            name="keywords"
            content="Descoperă secretele fascinante ale lumii apiculturii și producției de miere,
Ghid complet despre apicultură și beneficiile consumului de miere proaspătă,
Află cum să începi propria ta aventură în apicultură și să produci miere de calitate,
Explorăm tehnici moderne și tradiționale în apicultură pentru o producție optimă de miere,
Îmbogățește-ți cunoștințele despre biologia albinelor și ecosistemul lor vital,
Inspiră-te din practicile sustenabile de apicultură și protejarea albinelor,
Cumpără miere pură și naturală, direct de la producători apicultori pasionați,
Blog apicol dedicat pasionaților și începătorilor în apicultură,
Sfaturi utile pentru menținerea sănătății stupilor și a albinelor tale,
Înțelege importanța polenizării pentru ecosistem și alimentația umană,
Profilul unui apicultor experimentat și poveștile sale din lumea stupilor,
Despre noi - o echipă pasionată de apicultură și distribuirea mierii naturale,
Citește cele mai recente cercetări în domeniul sănătății albinelor și a amenințărilor la adresa lor,
Cum să recunoști mierea falsificată și să alegi produse autentice,
Stiri apicole proaspete din industrie și noutăți despre legislația în domeniu,
Explorăm beneficiile consumului regulat de miere asupra sănătății tale,
Metode de colectare și procesare a mierii pentru a păstra calitatea și prospețimea,
Catalog de echipamente apicole esențiale pentru începători,
Află cum să obții certificarea organică pentru mierea produsă,
Promovăm biodiversitatea prin protejarea albinelor și a habitatelor lor,
Galerie foto a minunatului univers al albinelor și stupilor,
Parteneriate cu fermieri locali pentru o miere autentică și sustenabilă,
Află cum să construiești stupi pentru albinele tale cu propriile tale mâini,
Catalog de flori și plante benefice pentru hrana albinelor și polenizare,
Aromă și nuanțe unice în mierea produsă în diferite regiuni geografice,
Împărtășim povești și experiențe din apicultura noastră familială,
Cum să creezi propriile produse cosmetice pe bază de miere,
Navighează prin resursele noastre informative despre apicultură și miere,
Te invităm să participi la atelierele noastre de apicultură și degustări de miere,
Află despre riscurile pesticidele asupra albinelor și soluții alternative,
Ghid pas cu pas pentru extragerea și ambalarea mierii proaspete,
Blog despre tehnici de îngrijire a albinelor în sezonul rece,
Cunoaște tehnici de luptă împotriva dăunătorilor din stupi,
Descoperă cum apicultura urbană contribuie la mediul înconjurător,
Bucură-te de beneficiile terapeutice ale mierii în medicina tradițională,
Află despre albinele melifere versus albinele sălbatice și rolul lor în ecosistem,
Cum să alegi locația potrivită pentru amplasarea stupilor tăi,
Inspiră-te din miturile și legende despre albine din culturile lumii,
Cursuri de apicultură pentru toate nivelurile de experiență,
Oportunități de voluntariat pentru a învăța mai multe despre apicultură,
Îmbunătățește-ți grădina cu plante atrăgătoare pentru albine și polenizatori,
Ghid pentru colectarea și conservarea propolisului, un alt dar al albinelor,
Miere monoflorală vs. poliflorală: alegerea perfectă pentru gustul tău,
Partajează-ne întrebările tale despre apicultură și miere în comunitatea noastră,
Protejarea albinelor pentru a asigura securitatea alimentară globală,
Calendarul lucrărilor de apicultură pe parcursul anotimpurilor,
Răspunsuri la cele mai frecvente întrebări despre apicultură și miere,
Învățăm despre dansul albinelor și comunicarea lor complexă,
Blog despre tehnici de multiplicare a familiilor de albine,
Descoperă variantele de miere cristalizată și cum să o redescoperi,
Metode de control al bolilor în stupi pentru a menține sănătatea albinelor,
Află cum apicultura poate fi o afacere sustenabilă și profitabilă,
Articole despre apiterapie și utilizarea produselor apicole în scopuri medicinale,
Experiențele noastre în recoltarea și producția de propolis,
Descoperă echipamente inovatoare pentru monitorizarea sănătății albinelor,
Află cum să devii un ambasador pentru protejarea albinelor în comunitatea ta,
Cazuri de succes în apicultura de precizie și tehnologie,
Rețete delicioase cu miere pentru o alimentație sănătoasă și gustată,
Cum să colectezi și să păstrezi polenul pentru beneficiile sale nutritive,
Poveștile apicultorilor din întreaga lume și diversitatea practicilor lor,
Catalog de flori rare și exotice care produc miere unică,
Cum să gestionezi enigmatica problemă a albinelor furioase,
Descoperă tendințele actuale în cercetarea apicolă și inovare,
Cum să recunoști și să îngrijești albinele regine,
Explorăm legătura dintre biodiversitate și sănătatea albinelor,
Ghid pentru inițierea copiilor în minunata lume a apiculturii,
Povestea mierii în culturile tradiționale și ritualurile lor,
Resurse gratuite pentru studiul profund al apiculturii și al albinelor,
Cum să previi și să tratezi stresul în coloniile de albine,
Produse inovatoare derivate din ceara de albine și miere,
Cum să realizezi propria ta vospă cu ingrediente naturale,
Experiențe personale ale apicultorilor în confruntarea cu schimbările climatice,
Află cum să fii un consumator informat atunci când cumperi miere,
Cum să recunoști semnele de intoxicare a albinelor cu pesticide,
Blog despre apicultura ca formă de terapie și relaxare,
Află cum să îmbini apicultura cu agricultura ecologică,
Catalog de plante medicinale cultivate alături de stupi,
Cum să creezi produse artizanale unice cu miere pentru cadouri,
Descoperă cum apicultura contribuie la menținerea echilibrului ecologic,
Tehnici de recoltare a veninului de albine pentru scopuri terapeutice,
Înțelege cum albinele contribuie la poluarea cruciată a plantelor,
Cum să prelungești durata de viață a albinelor lucrătoare,
Resurse pentru apicultorii urbani și modalități de a gestiona spațiul limitat,
Ghid pentru transformarea mierii cristalizate în starea sa lichidă,
Cum să îți dezvolți simțul gustului pentru a aprecia varietatea de miere,
Importanța conservării habitatelor naturale pentru supraviețuirea albinelor,
Află despre istoria apiculturii și importanța ei culturală,
Ghid pentru detectarea și tratarea bolilor parazitare ale albinelor,
Metode de întreținere a stupilor în zonele cu temperaturi extreme,
Cum să construiești parteneriate cu restaurante și magazine locale pentru distribuția de miere,
Înțelege ciclurile de viață ale albinelor și nevoile fiecărei etape,
Catalog de rețete tradiționale și moderne cu miere,
Cum să creezi un mediu favorabil pentru albine în grădina ta,
Îmbunătățește-ți cunoștințele despre comportamentul social al albinelor,
Cum să previi și să gestionezi riscurile de înțepături în timpul lucrului cu albinele,
Catalog de accesorii utile pentru protecția apicultorilor în timpul muncii,
Descoperă ce înseamnă să fii un apicultor responsabil în era modernă,
Cum să cunoști plantele toxice pentru albine și să le eviți,
Află despre apicultura tradițională în diferite regiuni ale lumii,
Împărtășește cu noi poveștile tale legate de albine și miere în comunitatea noastră online,
Apicultură,
Miere naturală,
Stupi,
Albine melifere,
Beneficii sănătate,
Producție de miere,
Ghid apicol,
Ecosistem,
Polenizare,
Protecția albinelor,
Albină regină,
Tehnici apicole,
Consum de miere,
Sfaturi apicultură,
Stupar,
Miere locală,
Produse apicole,
Apiterapie,
Stare de sănătate a albinelor,
Ceară de albine,
Mediu înconjurător,
Apicultori pasionați,
Tratamente naturale,
Educație apicolă,
Cultivare de flori pentru albine,
Tehnologie în apicultură,
Comunitate apicolă,
Miere monoflorală,
Polen,
Stiri apicole,
Mediu urban pentru albine,
Mirosul stupilor,
Produse cosmetice cu miere,
Istoria apiculturii,
Impactul pesticidelor,
Recoltare miere,
Produse artizanale,
Apicultură sustenabilă,
Cursuri apicole,
Albină lucrătoare,
Biodiversitate,
Propolis,
Calendar apicol,
Miere cristalizată,
Terapie cu venin de albine,
Schimbări climatice,
Habitat albină sălbatică,
Agroturism apicol,
Mirosul florilor,
Tehnici de creștere a familiilor de albine,
Miere ecologică,
Apicultura în grădină,
Produse cu propolis,
Polenizatori,
Mirosul fumului în stupi,
Produse naturale,
Păstrarea sănătății albinelor,
Gestionarea dăunătorilor,
Apicultura și mediul înconjurător,
Miere de manuk,
Retete culinare cu miere,
Ambarcațiuni din ceară de albine,
Conținut educativ,
Albină sălbatică,
Plante atrăgătoare pentru albine,
Bune practici apicole
Albină și polenizare,
Produse cosmetice naturale,
Sănătatea albinelor lucrătoare,
Ambalare produse apicole,
Povești de succes ale apicultorilor,
Tradiții apicole,
Albină și mediul înconjurător,
Ateliere apicole,
Calitatea mierii,
Mirosul florilor de primăvară,
Impactul albinelor în agricultură,
Biodiversitate și alimentație umană,
Sfaturi de marketing pentru apicultori,
Produse apicole premium,
Apicultura și turismul rural,
Meliferiță,
Plante medicinale și miere,
Apicultura urbană,
Mirosul ceară de albine,
Inițiere în apicultură,
Albină și natură,
Miere exotică,
Monitorizarea sănătății albinelor,
Importanța polenizării,
Miere și imunitate,
Stupi durabili,
Diverse tipuri de miere,
Produse derivate din miere,
Beneficiile polenului,
Apicultura ca terapie,
Tehnici de multiplicare a familiilor de albine,
Ceară și lumânări apicole,
Apicultura și conservarea biodiversității,
Riscuri și soluții în apicultură,
Mirosul mierii proaspete,
Apicultură tradițională vs. modernă,
Sustenabilitate în apicultură,
Produse apicole pentru sănătate și frumusețe,
Stupi în regiuni montane,
Comunități locale de apicultori,
Apicultura și economia locală,
Protejarea habitatelor albinelor,
Mirosul propolisului,
Apicultura ca formă de agricultură urbană,
Despre noi - echipa apicolă,
Miere și antioxidanți,
Apicultura și dezvoltarea durabilă,
Produse apicole tradiționale,
Apicultură pentru începători,
Mirosul florilor de vară,
Miere și bunăstare,
Miere în gastronomie,
Albină și ciclul naturii,
Boli apicole și prevenție,
Miere de floarea-soarelui,
Tehnici de control al bolilor în stupi,
Apicultura și poluarea mediului,
Miere și medicină alternativă,
Cursuri online de apicultură,
Produse cosmetice cu propolis,
Apicultura ca hobby,
Miere și echilibru nutrițional,
Apicultura și biodiversitatea florației,
Miere și răsfăț personal,
Gestionarea riscurilor în apicultură,
Albină și simbioză cu plantele,
Miere de salcâm,
Echipamente esențiale pentru apicultori,
Apicultura și sănătatea mediului,
Produse artizanale din ceară de albine,
Miere și gastronomie locală,
Apicultura ca formă de conservare ecologică,
Sănătatea albinelor și siguranța alimentară,
Miere în bucătăria tradițională,
Apicultura și biodiversitatea apelor,
Produse apicole pentru îngrijire personală,
Albină și diversitate floristică,
Miere de salcâm vs. miere poliflorală,
Apicultura și schimbările climatice,
Albină și ciclurile sezoniere,
Miere și imunitatea naturală,
Apicultura și relația om-natură,
Albină și polenizare în agricultura ecologică,
Miere ca ingredient în rețete culinare"
          />
        </Head>

        <NavBar />
        <Component {...pageProps} />
      </LanguageProvider>
    </>
  );
}
